# Generated by Django 3.2.8 on 2021-11-12 14:20

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CDA', models.CharField(blank=True, max_length=50)),
                ('Netflix', models.CharField(blank=True, max_length=50)),
                ('HboGO', models.CharField(blank=True, max_length=50)),
                ('AmazonPrime', models.CharField(blank=True, max_length=50)),
                ('HardDrive', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MovieTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, help_text='A label for URL config.', max_length=31, populate_from=['tag'])),
            ],
            options={
                'ordering': ['tag'],
            },
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Year', models.IntegerField()),
                ('Runtime', models.CharField(blank=True, max_length=30)),
                ('Genre', models.CharField(blank=True, max_length=30)),
                ('Director', models.CharField(blank=True, max_length=30)),
                ('Actors', models.CharField(blank=True, max_length=60)),
                ('Plot', models.TextField(blank=True, max_length=300)),
                ('user_comments', models.TextField(blank=True, max_length=200)),
                ('Awards', models.CharField(blank=True, max_length=250)),
                ('Poster', models.URLField(blank=True, max_length=250)),
                ('imdbRating', models.CharField(blank=True, max_length=4)),
                ('Metascore', models.CharField(blank=True, max_length=4)),
                ('imdbID', models.CharField(blank=True, max_length=10)),
                ('slug', models.SlugField(blank=True)),
                ('movieURL', models.URLField(blank=True, max_length=40)),
                ('Rating', models.IntegerField(choices=[(5, '5'), (4, '4'), (3, '3'), (2, '2'), (1, '1'), (0, '0')], default=0)),
                ('Location', models.CharField(choices=[('HARD DRIVE', 'HARD DRIVE'), ('CDA', 'CDA'), ('NETFLIX', 'NETFLIX')], default='', max_length=10)),
                ('watched', models.BooleanField(default=True)),
                ('movie_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movies.movielocation')),
                ('movie_tag', models.ManyToManyField(to='movies.MovieTag')),
            ],
            options={
                'unique_together': {('Title', 'Year')},
            },
        ),
    ]
