# Generated by Django 3.2.8 on 2021-11-02 13:44

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, unique=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, help_text='A label for URL config.', max_length=31, populate_from=['tag'])),
            ],
            options={
                'ordering': ['tag'],
            },
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Year', models.IntegerField()),
                ('Runtime', models.CharField(blank=True, max_length=30)),
                ('Genre', models.CharField(blank=True, max_length=30)),
                ('Director', models.CharField(blank=True, max_length=30)),
                ('Actors', models.CharField(blank=True, max_length=60)),
                ('Plot', models.TextField(blank=True, max_length=250)),
                ('Awards', models.CharField(blank=True, max_length=250)),
                ('Poster', models.URLField(blank=True, max_length=250)),
                ('imdbRating', models.CharField(blank=True, max_length=4)),
                ('Metascore', models.CharField(blank=True, max_length=4)),
                ('imdbID', models.CharField(blank=True, max_length=10)),
                ('Rating', models.IntegerField(choices=[(5, 'Very Good'), (4, 'Good'), (3, 'Average'), (2, 'Poor'), (1, 'Bad'), (0, 'Piece Of Shit')], default='')),
                ('Location', models.CharField(choices=[('Harddrive', 'Harddrive'), ('CDA', 'Cda'), ('Netflix', 'Netflix')], default='', max_length=10)),
                ('movieURL', models.URLField(blank=True, max_length=40)),
                ('movie_tag', models.ManyToManyField(to='movies.MovieTag')),
            ],
        ),
    ]
