# Generated by Django 3.2.8 on 2021-11-13 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='movie_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movies.movielocation', verbose_name='movie location'),
        ),
    ]
