# Generated by Django 3.2.8 on 2021-11-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movies_movie_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='movie_location',
        ),
        migrations.AddField(
            model_name='movies',
            name='AmazonPrime',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='movies',
            name='CDA',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='movies',
            name='HardDrive',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='movies',
            name='HboGO',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='movies',
            name='Netflix',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.DeleteModel(
            name='MovieLocation',
        ),
    ]
