# Generated by Django 3.2.8 on 2021-11-14 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20211114_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='Location',
        ),
    ]
