# Generated by Django 3.2.8 on 2021-11-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20211104_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='not_watched',
        ),
        migrations.AddField(
            model_name='movies',
            name='watched',
            field=models.BooleanField(default=True),
        ),
    ]
