# Generated by Django 3.2.8 on 2021-11-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20211107_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='user_comments',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='movies',
            name='Location',
            field=models.CharField(choices=[('HARD DRIVE', '<img src="/media/local_icos/hdd_ico.jpg">'), ('CDA', '<img src="/media/local_icos/cda_ico.jpg">'), ('NETFLIX', '<img src="/media/local_icos/flix_ico.jpg">')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='movies',
            name='Rating',
            field=models.IntegerField(choices=[(5, '<img src="/media/rating_icos/rating_5_ico.jpg">'), (4, '<img src="/media/rating_icos/rating_4_ico.jpg">'), (3, '<img src="/media/rating_icos/rating_3_ico.jpg">'), (2, '<img src="/media/rating_icos/rating_2_ico.jpg">'), (1, '<img src="/media/rating_icos/rating_1_ico.jpg">'), (0, '<img src="/media/rating_icos/rating_0_ico.jpg">')], default=''),
        ),
        migrations.AlterField(
            model_name='movietag',
            name='tag',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='movies',
            unique_together={('Title', 'Year')},
        ),
    ]
