# Generated by Django 3.2.8 on 2021-11-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20211108_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='Plot',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='movies',
            name='user_comments',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
