# Generated by Django 3.2.8 on 2021-11-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20211108_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='Plot',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
