# Generated by Django 3.2.8 on 2021-11-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_alter_movies_plot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='Location',
        ),
        migrations.AddField(
            model_name='movies',
            name='AmazonPrime',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='movies',
            name='CDA',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='movies',
            name='HardDrive',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='movies',
            name='HboGO',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='movies',
            name='Netflix',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
