# Generated by Django 3.2.8 on 2021-11-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_auto_20211116_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='AmazonPrime',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='movies',
            name='CDA',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='movies',
            name='HardDrive',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='movies',
            name='HboGO',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='movies',
            name='Netflix',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
